---
title: "04 Data Visualization"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---
# Challenge #1
## Cummulative Confirmed Covid Cases Worldwide

```{r}
library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library(lubridate)
library(tictoc)


covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

covid_data_world_tbl  <- covid_data_tbl%>%
  filter(iso_code== 'OWID_WRL')

covid_cases_world_tbl<- covid_data_world_tbl%>%
  select(date,total_cases)

covid_cases_world_tbl %>%
  ggplot(aes(x = date, y = total_cases, color = total_cases))+
  geom_line(size=2)+
  labs(
    title = "Covid Cases Worldwide",
    subtitle = "Confirmed Covid Cases based on the Data found here: https://covid.ourworldindata.org/",
    x = "Date",
    y = "Covid Cases",
    caption = "Cummulative confirmed Covid-Cases since the outbreak in Wuhan in late 2020"
  )
```

# Challenge #2
unfortunately I wasn't able to finish this exercise. My approach was to set up a Dataframe for each continent with the corresponding mortality rates and the locations (defined by either country or longitude/latitude). That worked out as planned to this point. The problem I had was to cummulate the mortality rate over time per country and to plot this onto the given map. To show you the code up the point that worked out, I've put it below as plain text.


## Code for challenge #2

covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

covid_data_world_tbl  <- covid_data_tbl%>%
  filter(iso_code== 'OWID_WRL')

covid_cases_world_tbl<- covid_data_world_tbl%>%
  select(date,total_cases)%>%
  mutate(date = ymd(date, label=TRUE))

#Mortality Rate Asia

covid_data_asia_tbl  <- covid_data_tbl%>%
  filter(continent== 'Asia')
covid_mort_asia_tbl<- covid_data_asia_tbl%>%
  select(date,total_deaths,total_cases,location)%>%
  mutate(mortality=total_deaths/total_cases)%>%
  select(date, mortality, location)

covid_data_SA_tbl <- covid_data_tbl%>%
  filter(continent== 'South America')
covid_mort_SA_tbl<- covid_data_SA_tbl%>%
  select(date,total_deaths,total_cases,location)%>%
  mutate(mortality=total_deaths/total_cases)%>%
  select(date, mortality, location)

covid_data_NA_tbl <- covid_data_tbl%>%
  filter(continent== 'North America')
covid_mort_NA_tbl<- covid_data_NA_tbl%>%
  select(date,total_deaths,total_cases,location)%>%
  mutate(mortality=total_deaths/total_cases)%>%
  select(date, mortality, location)

covid_data_Africa_tbl <- covid_data_tbl%>%
  filter(continent== 'Africa')
covid_mort_Africa_tbl<- covid_data_Africa_tbl%>%
  select(date,total_deaths,total_cases,location)%>%
  mutate(mortality=total_deaths/total_cases)%>%
  select(date, mortality, location)

covid_data_europe_tbl <-covid_data_tbl%>%
  filter(continent== 'Europe')
covid_mort_Europe_tbl <- covid_data_europe_tbl%>%
  select(date,total_deaths,total_cases,location)%>%
  mutate(mortality=total_deaths/total_cases)%>%
  select(date, mortality, location)

world <- map_data("world")%>%
  rename(
    location = region) 

combined_data_asia <- merge(x = covid_mort_asia_tbl, y = world, 
                       by    = "location", 
                       all.x = TRUE, 
                       all.y = FALSE)

combined_data_SA <- merge(x = covid_mort_SA_tbl, y = world, 
                            by    = "location", 
                            all.x = TRUE, 
                            all.y = FALSE)

combined_data_NA <- merge(x = covid_mort_NA_tbl, y = world, 
                            by    = "location", 
                            all.x = TRUE, 
                            all.y = FALSE)

combined_data_Africa <- merge(x = covid_mort_Africa_tbl, y = world, 
                            by    = "location", 
                            all.x = TRUE, 
                            all.y = FALSE)

combined_data_Europe <- merge(x = covid_mort_Europe_tbl, y = world, 
                            by    = "location", 
                            all.x = TRUE, 
                            all.y = FALSE)
